# Generated by Django 4.1 on 2024-01-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       
    ]
