# Generated by Django 4.1 on 2024-01-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcom_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPollingUnitResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_name', models.CharField(max_length=300)),
                ('pdp_votes', models.IntegerField()),
                ('acn_votes', models.IntegerField()),
                ('dpp_votes', models.IntegerField()),
                ('ppa_votes', models.IntegerField()),
                ('cdc_votes', models.IntegerField()),
                ('anpp_votes', models.IntegerField()),
                ('jp_votes', models.IntegerField()),
                ('labour_votes', models.IntegerField()),
                ('cpp_votes', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
